Added payment method De Cadeaukaart
paynl/opencart3-plugin pull request #12
Opened 2020-11-03 10:41 UTC by bryantvandenberg

2020-11-05 08:25 UTC, annevelden requested changes

2020-11-05 08:25 UTC, annevelden commented on README.md
> +| Tikkie | De Cadeaukaart | YourGift | Creditclick | Apple Pay |
Op deze manier komt hij onder de credit cards terecht, er moet een nieuwe rij gemaakt worden en dan moet hij onder YourGift.

2020-11-06 15:39 UTC, annevelden approved these changes

2020-11-09 07:37 UTC, kevinverschoor approved these changes

2020-11-17 10:20 UTC, closed without merging

2020-11-17 10:20 UTC, woutse commented
Double