ideal staat in de lijst met betaalmethode's in de backoffice  in kleine letters. Aanpassen naar: iDEAL
paynl/opencart3-plugin pull request #13
Opened 2020-11-09 10:17 UTC by bryantvandenberg

2020-11-11 12:23 UTC, annevelden approved these changes

2020-11-16 10:40 UTC, woutse requested changes
See comments

2020-11-16 10:40 UTC, woutse commented on upload/admin/language/en-gb/extension/payment/paynl_decadeaukaart.php
> +$_['heading_title'] = 'PAY. - De Cadeakaart';
Spelfout

2020-11-17 09:28 UTC, woutse approved these changes

2020-11-17 09:37 UTC, annevelden approved these changes

2020-11-17 10:18 UTC, merged