Add brand images and option to enable them
paynl/opencart3-plugin pull request #22
Opened 2021-08-04 13:33 UTC by kevinverschoor

2021-08-13 07:28 UTC, annevelden requested changes
full comment on the ticket

2021-08-13 07:38 UTC, annevelden approved these changes

2021-09-23 14:26 UTC, woutse approved these changes

2021-09-28 11:45 UTC, annevelden approved these changes

2021-09-28 13:42 UTC, merged